### ISSUE TITLE
Can not initialize protocol module before app is ready

### ISSUE THREAD

**Issue by havlicekdom** [yan-foto/electron-pug#3]
Hi,

since last update of electron-pug, my app stopped working, it always ends with the error message mentioned in title. It was working before, when I was using the 1.3.0 version. The longer error is shown in image below. As you can see, it mentions the electron-pug module. Can you please help me?

<img width="426" alt="screen shot 2016-05-20 at 10 48 29" src="https://cloud.githubusercontent.com/assets/12134986/15422408/c40a1872-1e78-11e6-98f9-81d3db431a99.png">

**Comment by yan-foto** [comment]
Yes! version `1.4.0` has been adapted to work with electron `>= 1.0`. Electron team removed a number of [deprecated APIs](https://github.com/electron/electron/pull/5373) and it was major release because it also broke some old APIs. Make sure that you have at least version `1.0` and give it another try. Otherwise I would keep on using `~1.3`.
